name: fiber-orientation

channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  # Python version
  - python=3.12

  # Core scientific computing
  - numpy
  - scipy
  - pandas

  # Machine learning
  - scikit-learn
  - scikit-image
  - pytorch
  - torchvision
  - torchsummary

  # Image processing
  - opencv
  - pillow

  # Visualization
  - matplotlib

  # Jupyter
  - jupyter
  - notebook

